---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myds
spec:
  selector:
    matchLabels:
      app: flightbooking
  template:
    metadata:
      labels:
        app: flightbooking
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80
