---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myds
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80




Suggestions:
 * list clusters with: kops get cluster
 * edit this cluster with: kops edit cluster chaitu.k8s.local
 * edit your node instance group: kops edit ig --name=chaitu.k8s.local nodes-us-east-1a
 * edit your control-plane instance group: kops edit ig --name=chaitu.k8s.local control-plane-us-east-1a
