apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-rq
  namespace: dinein
spec:
  hard:
    limits.cpu: "500m"
    requests.cpu: "150m"
    limits.memory: "64Mi"
    requests.memory: "32Mi"


vim pod.yml

apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: dinein
spec:
  containers:
    - name: cont2
      image: nginx
      resources:
        requests:
          memory: "10Mi"
          cpu: "100m"
        limits:
          memory: "15Mi"
          cpu: "150m"



kubectl get quota -n dinein
