---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataservice
  template:
    metadata:
      labels:
        app: dataservice
    spec:
      containers:
        - name: cont-2
          image: nginx
          ports:
            - containerPort: 80
            

 kubectl apply -f statefulset.yml         whenever changes happen in file we use this command
